package io.radimyassine.voitureservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;

/**
 * Vehicle Management Service - RESTful Microservice Application
 * 
 * <p>
 * This microservice manages vehicle inventory and maintains relationships with
 * client data
 * in the Vehicle Management Platform. It provides REST API endpoints for
 * vehicle operations
 * and integrates with the Client Service to establish vehicle-client
 * associations.
 * </p>
 * 
 * <h2>Key Technologies:</h2>
 * <ul>
 * <li>Spring Boot 3.1.5 - Application framework</li>
 * <li>Spring Data JPA - Data persistence layer</li>
 * <li>Spring Cloud Consul Discovery - Service registration and discovery</li>
 * <li>MySQL - Relational database for vehicle data storage</li>
 * <li>Spring Web - RESTful API implementation</li>
 * </ul>
 * 
 * <h2>Exposed Endpoints:</h2>
 * <ul>
 * <li>GET / - Service health check endpoint</li>
 * <li>GET /voitures - Retrieve all vehicles</li>
 * </ul>
 * 
 * <h2>Architecture Integration:</h2>
 * <p>
 * This service registers itself with Consul for service discovery and is
 * accessible
 * through the API Gateway (port 8888). It maintains its own MySQL database
 * schema
 * (Micro_VoitureDB) and can reference client data through the id_client foreign
 * key.
 * </p>
 * 
 * <h2>Data Model:</h2>
 * <p>
 * Each vehicle entity contains brand (marque), license plate (matricule),
 * model,
 * and a reference to the owning client (id_client).
 * </p>
 * 
 * @author Radim Yassine
 * @version 1.0.0
 * @since 2026-01-01
 */
@SpringBootApplication
@RestController
public class VoitureServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(VoitureServiceApplication.class, args);
	}

	@Autowired
	private VoitureRepository voitureRepository;

	@GetMapping("/")
	public String home() {
		return "Service Voiture";
	}

	@GetMapping("/voitures")
	public List<Voiture> getAllVoitures() {
		return voitureRepository.findAll();
	}
}

/**
 * Voiture (Vehicle) Entity - Domain Model
 * 
 * <p>
 * Represents a vehicle in the management system. Each vehicle is associated
 * with a client
 * through the id_client foreign key reference.
 * </p>
 * 
 * <h3>Database Mapping:</h3>
 * <ul>
 * <li>Table: voiture (auto-generated by JPA)</li>
 * <li>Database: Micro_VoitureDB</li>
 * <li>Primary Key: Auto-incremented ID</li>
 * <li>Foreign Key: id_client references Client entity</li>
 * </ul>
 * 
 * @author Radim Yassine
 */
@Entity
class Voiture {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	private String marque;
	private String matricule;
	private String model;
	private Long id_client;

	public Voiture() {
	}

	public Voiture(String marque, String matricule, String model, Long id_client) {
		this.marque = marque;
		this.matricule = matricule;
		this.model = model;
		this.id_client = id_client;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getMarque() {
		return marque;
	}

	public void setMarque(String marque) {
		this.marque = marque;
	}

	public String getMatricule() {
		return matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Long getId_client() {
		return id_client;
	}

	public void setId_client(Long id_client) {
		this.id_client = id_client;
	}
}

/**
 * Voiture Repository - Data Access Layer
 * 
 * <p>
 * Spring Data JPA repository interface for Voiture entity operations.
 * Provides standard CRUD operations and query methods for vehicle data
 * management.
 * </p>
 * 
 * <p>
 * This repository automatically implements common database operations
 * including:
 * findAll(), findById(), save(), delete(), etc.
 * </p>
 * 
 * @author Radim Yassine
 */
interface VoitureRepository extends JpaRepository<Voiture, Long> {
}
