package io.radimyassine.clientservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;

/**
 * Client Service - RESTful Microservice Application
 * 
 * <p>
 * This microservice is responsible for managing client data within the Vehicle
 * Management Platform.
 * It provides REST API endpoints for client operations and integrates with
 * other microservices
 * through the API Gateway and Consul service discovery.
 * </p>
 * 
 * <h2>Key Technologies:</h2>
 * <ul>
 * <li>Spring Boot 3.1.5 - Application framework</li>
 * <li>Spring Data JPA - Data persistence layer</li>
 * <li>Spring Cloud Consul Discovery - Service registration and discovery</li>
 * <li>MySQL - Relational database for client data storage</li>
 * <li>Spring Web - RESTful API implementation</li>
 * </ul>
 * 
 * <h2>Exposed Endpoints:</h2>
 * <ul>
 * <li>GET / - Service health check endpoint</li>
 * <li>GET /clients - Retrieve all clients</li>
 * </ul>
 * 
 * <h2>Architecture Integration:</h2>
 * <p>
 * This service registers itself with Consul for service discovery and is
 * accessible
 * through the API Gateway (port 8888). It maintains its own MySQL database
 * schema
 * (Micro_ClientDB) and communicates with other services via REST APIs.
 * </p>
 * 
 * @author Radim Yassine
 * @version 1.0.0
 * @since 2026-01-01
 */
@SpringBootApplication
@RestController
public class ClientServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(ClientServiceApplication.class, args);
	}

	@Autowired
	private ClientRepository clientRepository;

	@GetMapping("/")
	public String home() {
		return "Service Client";
	}

	@GetMapping("/clients")
	public List<Client> getAllClients() {
		return clientRepository.findAll();
	}
}

/**
 * Client Entity - Domain Model
 * 
 * <p>
 * Represents a client in the vehicle management system. Each client can be
 * associated
 * with multiple vehicles through the Vehicle Management Service.
 * </p>
 * 
 * <h3>Database Mapping:</h3>
 * <ul>
 * <li>Table: client (auto-generated by JPA)</li>
 * <li>Database: Micro_ClientDB</li>
 * <li>Primary Key: Auto-incremented ID</li>
 * </ul>
 * 
 * @author Radim Yassine
 */
@Entity
class Client {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	private String nom;
	private Float age;

	public Client() {
	}

	public Client(String nom, Float age) {
		this.nom = nom;
		this.age = age;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Float getAge() {
		return age;
	}

	public void setAge(Float age) {
		this.age = age;
	}
}

/**
 * Client Repository - Data Access Layer
 * 
 * <p>
 * Spring Data JPA repository interface for Client entity operations.
 * Provides standard CRUD operations and query methods for client data
 * management.
 * </p>
 * 
 * <p>
 * This repository automatically implements common database operations
 * including:
 * findAll(), findById(), save(), delete(), etc.
 * </p>
 * 
 * @author Radim Yassine
 */
interface ClientRepository extends JpaRepository<Client, Long> {
}
